apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:

      nodeSelector:
        kubernetes.io/hostname: gke-cluster-1-default-pool-477a13ea-q05s

      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - name: welcome-volume
              mountPath: /usr/share/nginx/html

      volumes:
        - name: welcome-volume
          configMap:
            name: welcome-web-content
