namespace: default

generatorOptions:
  disableNameSuffixHash: true

resources:
  - todo/deployment.yaml
  - todo/service.yaml
  - welcome/deployment.yaml
  - welcome/service.yaml

configMapGenerator:
  - name: todo-web-content
    files:
      - todo/web/index.html
      - todo/web/style.css
      - todo/web/app.js

  - name: welcome-web-content
    files:
      - welcome/web/index.html
      - welcome/web/style.css
