replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/neat-pagoda-477804-m8/helm-images/todo-helm-ui
  tag: "v1"

service:
  type: LoadBalancer
  port: 80

nodeSelector:
  kubernetes.io/hostname: gke-cluster-1-node-1-6df7b73c-nsr8
